{{ if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-monitor-app
spec:
  hostnames:
    - {{ .Values.hostname }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.parentRef.name }}
      sectionName: {{ .Values.gateway.parentRef.sectionName }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ .Release.Name }}-monitor-app
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.path }}
{{ end }}