apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-monitor-app"
  labels:
    app.kubernetes.io/component: monitor-app
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  selector:
    app.kubernetes.io/component: monitor-app
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: web
